Client
deadpanda-c/SnakeS pull request #4
Opened 2024-11-25 14:50 UTC by AntoninLaudon

2024-11-25 14:57 UTC, Vivelis commented on Client/CMakeLists.txt
> +add_compile_options(-Wall -Wextra -Wpedantic -Werror -fno-gnu-unique -g)
debug flag ?

2024-11-25 14:58 UTC, AntoninLaudon commented on Client/CMakeLists.txt
> +add_compile_options(-Wall -Wextra -Wpedantic -Werror -fno-gnu-unique -g)
oups valgrind

2024-11-25 14:59 UTC, Vivelis commented on Client/src/Core.cpp
> +Core::Core() {}
Did we need no parameter constructor ?

2024-11-25 14:59 UTC, Vivelis commented on Client/src/Core.hpp
> +        Core();
Did we need no parameter constructor ?

2024-11-25 15:01 UTC, AntoninLaudon commented on Client/src/Core.cpp
> +Core::Core() {}
alors c'etait pour le definir PUIS le setup dans le main, sinon je peux pas le definir a la premiere ligne

2024-11-25 15:15 UTC, Vivelis requested changes

2024-11-25 15:15 UTC, Vivelis commented on Client/src/Core.hpp
> +
```suggestion

```

2024-11-25 15:15 UTC, Vivelis commented on Client/src/Game.cpp
> +    }
shoold set texture to default value or return

2024-11-25 15:15 UTC, Vivelis commented on Client/src/Lobby.cpp
> +        cancelButton.setOutlineThickness(10);
I you can comment in code, you can create function.
Rule 42 of the programmer.

2024-11-25 15:15 UTC, Vivelis commented on Client/src/Lobby.cpp
> +        }
could use switch case instead of if
switch (_event.type)

2024-11-25 15:15 UTC, Vivelis commented on Client/src/Lobby.hpp
> +
void

2024-11-25 15:15 UTC, Vivelis commented on Client/src/Tools.cpp
> +    std::regex ipRegex("^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)(\\.(?!$)|$)){4}$");
just here to say regex are good

2024-11-25 15:15 UTC, Vivelis commented on Client/src/Tools.cpp
> +        return std::make_pair("__EXIT__", 1);
hmmmmm weird but ok

2024-12-03 09:28 UTC, Vivelis approved these changes

2024-12-03 09:28 UTC, merged